from postfixadmin:3.3.7-apache
RUN apt-get install nano
#installation de la DB plus configuration
run -e POSTFIXADMIN_DB_TYPE=mysqli \
           -e POSTFIXADMIN_DB_HOST=whatever \
           -e POSTFIXADMIN_DB_USER=user \
           -e POSTFIXADMIN_DB_PASSWORD=topsecret \
           -e POSTFIXADMIN_DB_NAME=postfixadmin \
           --name some-postfixadmin \
           -p 8080:80
           
CMD postfixadmin
